// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYmqpTQkLISEqxsHx3IsBoLJKXJBmGU4s',
    appId: '1:350537715505:web:9842af206d6ac4e1e8ea10',
    messagingSenderId: '350537715505',
    projectId: 'monitoring-parameter',
    authDomain: 'monitoring-parameter.firebaseapp.com',
    storageBucket: 'monitoring-parameter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhB4PIW82iws4OSK7RQA3Jb3PwEAcMQY',
    appId: '1:350537715505:android:2138777f683eebb5e8ea10',
    messagingSenderId: '350537715505',
    projectId: 'monitoring-parameter',
    storageBucket: 'monitoring-parameter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWLvYSlnOLn1DgqRWPYVg9XIySqc0Eu8',
    appId: '1:350537715505:ios:96448f35e28a012ce8ea10',
    messagingSenderId: '350537715505',
    projectId: 'monitoring-parameter',
    storageBucket: 'monitoring-parameter.appspot.com',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnWLvYSlnOLn1DgqRWPYVg9XIySqc0Eu8',
    appId: '1:350537715505:ios:5d50488d675e6e3ce8ea10',
    messagingSenderId: '350537715505',
    projectId: 'monitoring-parameter',
    storageBucket: 'monitoring-parameter.appspot.com',
    iosBundleId: 'com.example.skripsi.RunnerTests',
  );
}
